kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: gitea.7willows.com/7willows/node-builder:latest
  commands:
    - npm install
    - npm run build:prod
    - npm run build:defs
    - npm publish
#  when:
#   event:
#     tag
  when:
    ref:
    - refs/tags/^v[0-9]*[.][0-9]*[.][0-9]*$

image_pull_secrets:
- dockerconfig
