image: node:latest

publish:
  script:
    - npm config set -- '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${NPM_TOKEN}"
    - npm config set -- '//gitlab.com/api/v4/packages/npm/:_authToken' "$NPM_TOKEN";
    - npm config set @7willows:registry=https://gitlab.com/api/v4/packages/npm/
    - npm install
    - npm run build
    - npm publish
  only:
    - tags