image: node:latest

publish:
  script:
    - npm config set -- '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${NPM_TOKEN}"
    - npm install
    - npm run build
    - npm publish
  only:
    - tags